name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          BASE_URL=https://www.cnnic.cn/NMediaFile/domain_list
          FILES=(
            1todayDel.txt
            future1todayDel.txt
            future2todayDel.txt
          )
          for file in ${FILES[@]}; do
            url=$BASE_URL/$file
            wget -q -O /tmp/$file $url
            date=$(grep -m 1 -oP '\d{4}-\d{2}-\d{2}' /tmp/$file)
            if (($? == 0)); then
              mkdir -p archives/$date
              mv -v /tmp/$file archives/$date
            fi
          done
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [[ -z "$(git status --porcelain)" ]]; then 
            echo 'nothing to commit'
          else 
            git add archives
            git commit -m "updated at $(date +%FT%T)"
            git push
          fi
      - shell: bash
        run: |
          curl -sSL https://api.github.com/repos/${{ github.repository }}/commits/HEAD \
            | jq -e 'now-(.commit.author.date|fromdateiso8601)<3600*36'
      - if: ${{ failure() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          channel-id: github
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "title": "${{ github.repository }}",
                  "title_link": "https://github.com/${{ github.repository }}",
                  "text": "Too Bad",
                  "fields": [
                    {
                      "title": "Status",
                      "value": "${{ job.status }}",
                      "short": true
                    }
                  ],
                  "footer": "Github Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

